GET http://localhost:1337/api/bowtie/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzAxNjc2NDgsImRhdGEiOiJrZW5ueUBsb2dnaW5zLmNvbSIsImlhdCI6MTUzMDE2NDA0OH0.159xlGMrveGdXt-g9Ap9ZQ2OJtEpREvHkrjQAiaPsXg